import { createElement, createRef } from 'react';
import { createRoot } from 'react-dom/client';
import { jsPDF } from 'jspdf';
import ReportRenderHost from '../components/ReportRenderHost';
import { hasStateMachine, generateJavaCode } from './javaCodeGen';
import { buildSET } from './symbolicExecution';
import { generateAllTestsFiles } from './mbtCodeGen';
import { PdfWriter } from './pdfWriter';

// Spins up a throwaway React root — deliberately OUTSIDE the main app tree
// (not mounted anywhere under <App/>), so ReportRenderHost's own mounted
// canvases never compete with whatever the user is actually looking at
// (e.g. a stray Delete keypress hitting two mounted StateMachineCanvases
// at once). Its diagram-driving calls (setMode/switchInstanceModel/
// setCapsule) DO share the same underlying Zustand stores as the live app
// though — that part's unavoidable and matches this session's earlier
// deselect-before-export trade-off: generating a report can briefly
// perturb whatever the live Structural/Behavioural view is showing.
function mountReportRenderHost() {
  const container = document.createElement('div');
  document.body.appendChild(container);
  const root = createRoot(container);
  const hostRef = createRef();
  root.render(createElement(ReportRenderHost, { ref: hostRef }));
  return {
    hostRef,
    cleanup() {
      root.unmount();
      container.remove();
    },
  };
}

function embedSourceFiles(w, files) {
  for (const f of files) {
    w.newPage();
    w.subheading(f.path);
    for (const line of f.content.split('\n')) w.line(line, { size: 8, mono: true });
  }
}

// Builds and downloads the full meta-model report — every section the
// professor asked for (meta-model, instance models, composite structure,
// state machines, generated code, the SET, generated tests), each
// individually toggleable via `selectedKeys`. Diagram sections are real
// rendered images (not text summaries), captured by mounting the live
// app's own canvas components off-screen one at a time (ReportRenderHost)
// and reusing this session's captureFlowImageDataUrl() — the same code
// path "Export JPG/SVG" already uses, just without triggering a download
// per diagram.
export async function generateFullReport({ metaModel, instanceModels, userName, selectedKeys }) {
  const has = (key) => selectedKeys.includes(key);
  const capsuleClasses = metaModel.classes.filter((c) => hasStateMachine(c, metaModel));

  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  const w = new PdfWriter(doc);

  // ── Title page ──────────────────────────────────────────────────────────
  doc.setFont(undefined, 'bold');
  doc.setFontSize(24);
  doc.text(metaModel.name || 'Untitled Model', w.margin, 200);
  doc.setFont(undefined, 'normal');
  doc.setFontSize(13);
  doc.setTextColor('#555555');
  doc.text(`Date: ${new Date().toLocaleDateString()}`, w.margin, 232);
  if (userName) doc.text(`Generated by: ${userName}`, w.margin, 250);
  doc.setTextColor('#000000');

  const { hostRef, cleanup } = mountReportRenderHost();
  try {
    // Let the host's own first mount/effects settle before driving it —
    // its four canvases each need their own ReactFlowProvider/Background
    // set up before a capture call would find anything meaningful.
    await new Promise((resolve) => setTimeout(resolve, 100));

    if (has('metamodel')) {
      w.newPage();
      w.heading('Meta-Model');
      const { dataUrl, width, height } = await hostRef.current.captureMetaModel();
      w.image(dataUrl, width, height);
    }

    if (has('instances')) {
      for (let i = 0; i < instanceModels.length; i++) {
        w.newPage();
        w.heading(`Instance Model: ${instanceModels[i].name}`);
        const { dataUrl, width, height } = await hostRef.current.captureInstanceModel(i);
        w.image(dataUrl, width, height);
      }
      if (instanceModels.length === 0) w.line('(no instance models)', { color: '#666666' });
    }

    if (has('structure')) {
      for (let i = 0; i < instanceModels.length; i++) {
        w.newPage();
        w.heading(`Composite Structure: ${instanceModels[i].name}`);
        try {
          const { dataUrl, width, height } = await hostRef.current.captureCompositeStructure(i);
          w.image(dataUrl, width, height);
        } catch (err) {
          w.line(`(nothing to show — ${err.message})`, { color: '#888888' });
        }
      }
      if (instanceModels.length === 0) w.line('(no instance models)', { color: '#666666' });
    }

    if (has('statemachines')) {
      for (const cls of capsuleClasses) {
        w.newPage();
        w.heading(`State Machine: ${cls.name}`);
        try {
          const { dataUrl, width, height } = await hostRef.current.captureStateMachine(cls.id);
          w.image(dataUrl, width, height);
        } catch (err) {
          w.line(`(nothing to show — ${err.message})`, { color: '#888888' });
        }
      }
      if (capsuleClasses.length === 0) w.line('(no capsule has a state machine)', { color: '#666666' });
    }

    if (has('code')) {
      w.newPage();
      w.heading('Generated Code');
      const files = generateJavaCode(metaModel, instanceModels, 'all');
      embedSourceFiles(w, files);
    }

    if (has('set')) {
      for (const cls of capsuleClasses) {
        w.newPage();
        w.heading(`Symbolic Execution Tree: ${cls.name}`);
        try {
          const { dataUrl, width, height } = await hostRef.current.captureSET(cls.id, metaModel);
          w.image(dataUrl, width, height);
        } catch (err) {
          w.line(`(nothing to show — ${err.message})`, { color: '#888888' });
        }
      }
      if (capsuleClasses.length === 0) w.line('(no capsule has a state machine)', { color: '#666666' });
    }

    if (has('tests')) {
      for (const cls of capsuleClasses) {
        const setResult = buildSET(cls.id, metaModel);
        const leaves = [...setResult.nodesById.values()].filter((n) => n.status !== 'open');
        if (leaves.length === 0) continue;
        const { files } = generateAllTestsFiles(setResult, cls, metaModel);
        w.newPage();
        w.heading(`Generated Tests: ${cls.name}`);
        embedSourceFiles(w, files);
      }
    }
  } finally {
    cleanup();
  }

  const safeName = (metaModel.name || 'model').replace(/[^a-z0-9_-]+/gi, '_');
  doc.save(`${safeName}-report.pdf`);
}
